{% set name = "solar_system_ephemerides" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/solar_system_ephemerides-{{ version }}.tar.gz
  sha256: 23c7e89e0b7db192f609d8abc6550b51f473743de06194408ae07473ffa22d29

build:
  entry_points:
    - create_solar_system_ephemeris = solar_system_ephemerides.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6,<4.0
    - setuptools >=61
    - setuptools-scm >=6.2
    - wheel
    - pip
  run:
    - python >=3.6,<4.0
    - astropy
    - jplephem

test:
  imports:
    - solar_system_ephemerides
  commands:
    - pip check
    - create_solar_system_ephemeris --help
  requires:
    - pip

about:
  home: https://github.com/cwinpy/solar-system-ephemerides
  summary: Solar system ephemeris files
  license: MIT
  license_file: LICENSE
  description: |
    This package contains solar system ephemeris files for use in continuous gravitational-wave searches.

extra:
  recipe-maintainers:
    - mattpitkin
